web_resource_g2g/internal_market/urls.py
from django.urls import path
from . import views

app_name = 'internal_market'

urlpatterns = [
    path('market/', views.main_page, name='main_page'),
    path('create_order_from_form/', views.create_order_from_form, name='create_order_from_form'),

]

web_resource_g2g/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.start_page, name='start_page'),
    path('update_table_data/', views.update_table_data, name='update_table_data'),
    path('add_server/', views.add_server, name='add_server'),
    path('handle_option_change/', views.handle_option_change, name='handle_option_change'),
    path('show_order_info/', views.show_order_info, name='show_order_info'),
    path('upload_video/<int:sold_order_number>/', views.upload_video, name='upload_video'),
    path('history_orders/', views.show_history_orders, name='history_orders'),
    path('balance/', views.show_balance, name='balance'),
    path("delete_server/", views.delete_server, name="delete_server"),
    path("my_services/", views.my_services, name="my_services"),
]

web_resource_g2g/users/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView
from django.urls import reverse_lazy

app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('accounts/profile/', views.profile, name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('logout/', views.logout_view, name='logout'),
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='reset_password'),
    path('password_reset/reset_password_sent/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),


]

web_resource_g2g/web_resource_g2g/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("", include("users.urls")),
    path("internal_market/", include("internal_market.urls")),
] +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_resource_g2g/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
   
    class Meta:
        model = User
        fields = ['username', 'email']

class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

class SearchForm(forms.Form):
    keyword = forms.CharField(label='Keyword', max_length=100)  

web_resource_g2g/users/views.py
import requests
from django import forms
from django.contrib.auth import authenticate, update_session_auth_hash
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.urls import reverse
from django.views import View
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from .forms import RegisterForm
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


def profile(request):
    return render(request, 'users/profile.html')


class RegisterView(View):
    template_name = 'users/register.html'
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to='/')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, context={'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'Greetings {username}, your account has been successfully registered')
            return redirect(to='users:login')
        return render(request, self.template_name, context={'form': form})


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    error_messages = {
        'invalid_login': "Invalid username or password. Please try again.",
        'inactive': "This account is inactive.",
    }

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(username=username, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(self.error_messages['invalid_login'], code='invalid_login')
            elif not self.user_cache.is_active:
                raise forms.ValidationError(self.error_messages['inactive'], code='inactive')

        return self.cleaned_data


class CustomLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = LoginForm

    def get_success_url(self):
        return '/'


def change_password(request):
    template_name = 'users/change_password.html'
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password has been successfully changed!')
            return redirect('/accounts/profile/')
        else:
            messages.error(request, 'The old or new password is not valid.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, template_name, {'form': form})


def logout_view(request):
    logout(request)
    return redirect(reverse('users:login'))


class CustomPasswordResetView(PasswordResetView):
    template_name = 'users/reset_password.html'
    email_template_name = 'password_reset_email.html'
    subject_template_name = 'password_reset_subject.txt'
    success_url = 'reset_password_sent'


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'


def index(request):
    return render(request, 'users/index.html')

web_resource_g2g/users/templates/users/base.html
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% load static %}
  <!-- Basic -->
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <!-- Site Metas -->
  <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/gif" />
  <meta name="keywords" content=""/>
  <meta name="description" content=""/>
  <meta name="author" content=""/>

  <style>
	.center-container {
		text-align: center;
	}
	table {
		margin: 0 auto;
		width: 80%; /* Or set a fixed width if desired */
		border-collapse: collapse; /* Ensures borders between cells */
		background-color: rgba(255, 255, 255, 0);

	}
	th, td {
		border: 1px solid #ddd; /* Border style and color for cells */
		padding: 5px; /* Spacing between cell content and borders */
		background-color: transparent;

	}
	.price-column {
		 width: 200px;
	}

	@keyframes pulse-blink {
	0% {
	  background-color: green;
	  transform: scale(1);
	}
	50% {
	  background-color: yellow;
	  transform: scale(2);
	}
	100% {
	  background-color: green;
	  transform: scale(1);
	}
  }

  .status-circle {
	display: inline-block;
	width: 15px;
	height: 15px;
	border-radius: 50%;
  }

  .status-circle.blinking {
	animation: pulse-blink 2s infinite ease-in-out; /* 2s тривалість, нескінченно */
  }

}
  </style>


  <title>Bets</title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet"/>

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet"/>
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet"/>
  <!--  <link href="{% static 'css/bootstrap.css.map' %}" rel="stylesheet"/>-->
  <!--  <link href="{% static 'css/js/bootstrap.js.map' %}" rel="stylesheet"/>-->
</head>
<body style="background-image: url('{% static 'images/background.jpg' %}'); background-size: cover; background-repeat: no-repeat;">
<div style="position: absolute; top: 0; left: 0; right: 0; bottom: 0; background-color: rgba(255, 255, 255, 0.5);"></div>

<div class="hero_area">
  <!-- header section strats -->
  <header class="header_section long_section px-0">
    <nav class="navbar navbar-expand-lg custom_nav-container">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex justify-content-between align-items-center w-100">
                    {% if user.is_authenticated %}
                        <div>
                            <a class="navbar-brand" href="{% url 'main:start_page' %}">Головна</a>
                            <a class="navbar-brand" href="">Оновити сторінку</a>

                        </div>
                        <div>
                            <div class="d-flex align-items-center">
                                <span style="color: lightblue;">Баланс {{user_balance}} $</span>
                                <a href="{% url 'main:show_order_info'%}" class="nav-link me-3">Активне замовлення</a>
                                <a href="{% url 'main:my_services' %}" class="nav-link me-3">Мої послуги</a>
                                <a href="{% url 'internal_market:main_page' %}" class="nav-link me-3">Внутрішній Ринок</a>
                                <a href="{% url 'main:history_orders' %}" class="nav-link me-3">Історія замовлень</a>
                                <a href="/" class="nav-link me-3">{{user.username}}</a>
                                <form action="{% url 'users:logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-link nav-link">Log Out</button>
                                </form>
                            </div>
                        </div>
                    {% else %} {# Блок для неавторизованих користувачів #}
                        <div></div> {# Пустий div, щоб зберегти структуру розмітки #}
                        <div class="quote_btn-container">
                            <a href="/login">
                                <span>Login</span>
                                <i class="fa fa-user" aria-hidden="true"></i>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
  </header>

  {% block content %}
  {% endblock %}

</div>
<!-- load js -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

</body>

</html>

web_resource_g2g/users/templates/users/change_password.html
{% extends 'users/base.html' %}

{% block content %}

    <div class="container mt-5">
        <h2>Change Password</h2>
        <form method="post">
            {% csrf_token %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="form-group">
                <label for="id_old_password">Old Password:</label>
                {{ form.old_password }}
            </div>
            <div class="form-group">
                <label for="id_new_password1">New Password:</label>
                {{ form.new_password1 }}
            </div>
            <div class="form-group">
                <label for="id_new_password2">Confirm New Password:</label>
                {{ form.new_password2 }}
            </div>
            <div class="form-group">
                <button type="submit">Change Password</button>
            </div>
        </form>
    </div>
{% endblock %}

web_resource_g2g/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    <title>Personal Assistant</title>
    <style>
        .news-header {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row bg-primary py-3 mb-3">
            <div class="col-md-8">
                <h1 class="text-white">
                    <a href="/" class="text-decoration-none text-white">Personal Assistant</a>
                </h1>
            </div>
            <div class="col-md-4 d-flex align-items-center justify-content-end">
                {% if user.is_authenticated %}
                <form action="logout/" method="post">
                        {% csrf_token %}
                        <a href="accounts/profile/" class="btn btn-light me-2">{{ user.username }}</a>
                        <button type="submit" class="btn btn-light me-2">Log Out</button>
                    </form>
                {% else %}
                    <a href="/register" class="btn btn-light me-2">Sign Up</a>
                    <a href="/login" class="btn btn-light me-2">Login</a>
                {% endif %}
            </div>
            <div class="col-md-4 search-form">
                <form method="GET" action="" class="d-flex">
                    <input type="text" name="search_query" placeholder="Search">
                    <button type="submit" class="btn btn-light">Search</button>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="news-section" id="news-section">
                    <h2 class="news-header">Fresh News</h2>
                    <!-- Search form -->
                    <ul class="news-list" style="display: none;">
                        {% for news_item in news_list %}
                        <li>
                            <h3><a href="{{ news_item.link }}">{{ news_item.title }}</a></h3>
                            <p>{{ news_item.content }}</p>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var newsHeader = document.querySelector('.news-header');
            var newsList = document.querySelector('.news-list');

            newsHeader.addEventListener('click', function() {
                if (newsList.style.display === 'none') {
                    newsList.style.display = 'block';
                } else {
                    newsList.style.display = 'none';
                }
            });

            var personalAssistant = document.querySelector('.text-decoration-none');
            personalAssistant.addEventListener('click', function() {
                if (newsList.style.display === 'block') {
                    newsList.style.display = 'none';
                }
            });
        });
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-B6sLOLr/6+oqM5fCMtG5qH0cSAO6qDl3jI4gW2G14NC7Glg7mGFPp4XuhFffTJf3" crossorigin="anonymous"></script>
</body>
</html>

web_resource_g2g/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="container mt-5">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <li class="success-message">{{ message }}</li>
                    {% elif message.tags == 'error' %}
                        <li class="error-message">{{ message }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <div class="form-group">
                <label for="username">Username:</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                {{ form.password }}
            </div>
            <div class="form-group">
                <button type="submit">Login</button>
                <a href="/password_reset" class="recover-password-link">Forgot your password?</a>
            </div>
        </form>
    </div>
{% endblock %}

web_resource_g2g/users/templates/users/password_reset_complete.html
{% extends 'users/base.html' %}

{% block content %}
<div class="container mt-5 text-center">
    <h2>Password reset has been completed successfully!</h2>
    <a href="/login" class="btn btn-primary me-2">Login</a>
</div>
{% endblock %}

web_resource_g2g/users/templates/users/password_reset_confirm.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="container mt-5 text-center">
        <h1>Password Reset</h1>
        <p>Enter your new password below:</p>
        <form method="post">
            <div class="form-group">
                {% csrf_token %}
                {{ form }}
            </div>
            <div class="form-group">
                <button type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock %}

web_resource_g2g/users/templates/users/password_reset_done.html
{% extends 'users/base.html' %}

{% block content %}
<div class="container mt-5 text-center">
    <h2>Password reset instructions sent</h2>
    <p>Check your email and follow the instructions to reset your password.</p>
</div>
{% endblock %}

web_resource_g2g/users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    <title>Personal Assistant</title>

    <style>
        .big-button {
            font-size: 24px;
            padding: 20px 40px;
            margin-top: 20px;
        }
        .big-button:hover {
            background-color: blue;
        }
        .center-container {
            position: absolute;
            bottom: 65%;
            left: 50%;
            transform: translateX(-50%);
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
            text-align: center;
        }
        .button-wrapper {
            margin: 0 10px;
        }
    </style>
</head>
<body>
    <div class="container-fluid">
        <div class="row bg-primary py-3">
            <div class="col-md-8">
                <h1 class="text-white">
                    <a href="/" class="text-decoration-none text-white">Personal Assistant</a>
                </h1>
            </div>
            <div class="col-md-4 d-flex align-items-center justify-content-end">
                <form id="logout-form" action="/logout/" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-light me-2">Log Out</button>
                </form>
                <a href="/change_password" class="btn btn-light me-2">Change password</a>
            </div>
        </div>
    </div>

    <div class="center-container">
        <div class="button-wrapper">
            <p>Contact book</p>
            <a href="/content" class="btn btn-warning big-button">Contact</a>
        </div>
        <div class="button-wrapper">
            <p>Notes</p>
            <a href="/notes" class="btn btn-warning big-button">Notes</a>
        </div>
        <div class="button-wrapper">
            <p>File storage</p>
            <a href="/files/listfiles" class="btn btn-warning big-button">Files</a>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-B6sLOLr/6+oqM5fCMtG5qH0cSAO6qDl3jI4gW2G14NC7Glg7mGFPp4XuhFffTJf3" crossorigin="anonymous"></script>
</body>
</html>

web_resource_g2g/users/templates/users/register.html
{% extends 'users/base.html' %}

{% block content %}

<div class="container mt-5">
    <h2 class="text-center">Register User</h2>
    <form method="post" class="form-container">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% if field.errors %}
            <div class="text-danger">
                {% for error in field.errors %}
                {{ error }}
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

web_resource_g2g/users/templates/users/reset_password.html
{% extends 'users/base.html' %}

{% block content %}
<div class="container mt-5 text-center">
    <h2>Restore Password</h2>
    <form method="post">
      <div class="form-group">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset Password</button>
      </div>
    </form>
</div>
{% endblock %}