web_resource_g2g/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.start_page, name='start_page'),
    path('update_table_data/', views.update_table_data, name='update_table_data'),
    path('add_server/', views.add_server, name='add_server'),
    path('handle_option_change/', views.handle_option_change, name='handle_option_change'),
    path('show_order_info/', views.show_order_info, name='show_order_info'),
    path('upload_video/<int:sold_order_number>/', views.upload_video, name='upload_video'),
    path('history_orders/', views.show_history_orders, name='history_orders'),
    path('balance/', views.show_balance, name='balance'),
    path("delete_server/", views.delete_server, name="delete_server"),
    path("my_services/", views.my_services, name="my_services"),
]

web_resource_g2g/web_resource_g2g/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("", include("users.urls")),
    path("internal_market/", include("internal_market.urls")),
] +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_resource_g2g/main/views.py
import json
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseNotAllowed, HttpResponse
from django.shortcuts import render, redirect
from main import crud
from main import calculate_commissions_crud as commissions_crud
from .utils.logger_config import logger


from django.shortcuts import render
import json


@login_required(login_url='users:login')
def start_page(request):
    if request.method == 'GET':
        user_id = request.user.id
        all_bets = crud.get_main_data_from_table(user_id)

        servers = crud.query_servers()
        games = set(server.game_name for server in servers)
        regions = set(server.region for server in servers)

        grouped_data_db = crud.get_grouped_data(servers)
        grouped_data = json.dumps(grouped_data_db)

        # Перевірка, чи all_bets не є порожнім
        if all_bets:
            double_add = [{'server_name': server.get('server_name', ''),
                           'game_name': server.get('game_name', '')} for server in all_bets]
        else:
            double_add = []  # Якщо all_bets порожній, double_add також буде порожнім

        context = {
            "bets_list": all_bets if all_bets else [],  # Перевірка на порожній all_bets
            'games': games,
            'regions': regions,
            'servers_json': grouped_data,
            'double_add': double_add  # Тепер це список, а не JSON-рядок
        }

        return render(request, 'main/index.html', context)


def update_table_data(request):
    if request.method == 'POST':
        user_id = request.user.id
        data = json.loads(request.body)
        logger.info(data)
        new_price = crud.update_price_delivery(data, user_id)
        logger.info(new_price)
        return JsonResponse({'success': True, 'new_price': new_price})
    return HttpResponseNotAllowed(['POST'])


def add_server(request):
    if request.method == 'POST':
        add_server_info = json.loads(request.body)

        add_server_info['auth_user_id'] = request.user.id
        logger.info(f"add_server_info__{add_server_info}")
        crud.add_server_to_db(add_server_info)

    return JsonResponse({'success': True})


def handle_option_change(request):
    logger.info("inside handle_option_change")
    payload = json.loads(request.body)
    offer_id = payload["row_id"]
    action = payload["action"]
    logger.info(f'Change option__{action} for__{offer_id},')
    if action == 'delete':
        crud.delete_server_from_list(offer_id)
    else:
        crud.pause_offer(offer_id, action)
    return JsonResponse({'success': True})


@login_required(login_url='users:login')
def show_order_info(request):
    user_id = request.user.id

    order_info = crud.get_order_info(user_id)
    if order_info is None:
        return render(request, 'main/not_found_order.html')

    sold_order_number = order_info.sold_order_number
    price_unit = order_info.earned_without_admins_commission / order_info.quantity
    return render(request, 'main/show_order_info.html', context={"order": order_info,
                                                                 "sold_order_number": sold_order_number,
                                                                 "price_unit": round(price_unit, 2)})


def upload_video(request, sold_order_number):
    logger.info(f"sold_order_number__{sold_order_number}")
    user = request.user.id

    if request.method == 'POST':
        if 'video' in request.FILES:
            video_file = request.FILES['video']
            sent_gold = int(request.POST.get('sent_gold'))

            try:
                # Збереження файлу
                filename, sold_order = crud.create_video_filename(request, sold_order_number)
                filepath = os.path.join(settings.MEDIA_ROOT, 'videos', filename)  # Шлях до папки videos
                with open(filepath, 'wb+') as destination:
                    for chunk in video_file.chunks():
                        destination.write(chunk)
                logger.info(f"filepath__{filepath}")
                response = crud.update_sold_order_when_video_download(user, sold_order, filepath, sent_gold)
                logger.info(f"response__{response}")

                return redirect('main:start_page')
            except Exception as e:
                messages.success(request, 'Error saving video')

        else:
            messages.error(request, 'Будь ласка, виберіть файл.')


@login_required(login_url='users:login')
def show_history_orders(request):
    user_id = request.user.id
    payment_status = request.GET.get('payment_status', '')  # Отримуємо параметр фільтрації

    # Отримуємо замовлення з урахуванням фільтрації
    sold_orders = crud.get_sold_orders_for_history(user_id)
    internal_orders = crud.get_internal_orders_for_history(user_id)
    orders_with_balance = crud.get_orders_with_balance(user_id, sold_orders, internal_orders)
    logger.info(f"orders_with_balance__{orders_with_balance}")

    # Фільтрація за статусом виплати
    if payment_status:
        if payment_status == "charged_to_payment":
            orders_with_balance = [order for order in orders_with_balance if order['order'].charged_to_payment
                                   and not order['order'].paid_in_salary]
        elif payment_status == "paid_in_salary":
            orders_with_balance = [order for order in orders_with_balance if order['order'].charged_to_payment
                                   and order['order'].paid_in_salary]
        elif payment_status == "cancelled":
            orders_with_balance = [order for order in orders_with_balance
                                   if order['order'].status == "CANCEL_REQUESTED"]
        elif payment_status == "no_info":
            orders_with_balance = [order for order in orders_with_balance
                                   if not order['order'].charged_to_payment and not order['order'].paid_in_salary]

    return render(request, 'main/show_history.html', context={"orders_history": orders_with_balance})


def show_balance(request):
    balance = crud.get_balance(request.user.id)
    logger.info(f"balance__{balance}")
    return render(request, 'users/base.html', context={'user_balance': round(balance, 3)})


def delete_server(request):
    data = json.loads(request.body)
    row_id = data.get('row_id')
    crud.delete_server_from_list(row_id)
    return JsonResponse({"success": True})


@login_required(login_url='users:login')
def my_services(request):
    user_id = request.user.id
    my_service_commission_list = commissions_crud.get_my_service_list(user_id)
    my_clients_provide_service = crud.get_clients_provide_service(user_id)
    logger.info(f"my_clients_provide_service__{my_clients_provide_service}")
    return render(request, 'main/my_services.html', context={"my_services": my_service_commission_list,
                                                             'my_clients_provide_service': my_clients_provide_service})

web_resource_g2g/main/templates/main/about.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="images/fevicon.png" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Edgecut</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet" />

  <!-- font awesome style -->
  <link href="css/font-awesome.min.css" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="css/responsive.css" rel="stylesheet" />

</head>

<body class="sub_page">

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section long_section px-0">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="index.html">
          <span>
            Edgecut
          </span>
        </a>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class=""> </span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
            <ul class="navbar-nav  ">
              <li class="nav-item ">
                <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="about.html"> About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="furniture.html">Furnitures</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="blog.html">Blog</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="contact.html">Contact Us</a>
              </li>
            </ul>
          </div>
          <div class="quote_btn-container">
            <a href="">
              <span>
                Login
              </span>
              <i class="fa fa-user" aria-hidden="true"></i>
            </a>
            <form class="form-inline">
              <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                <i class="fa fa-search" aria-hidden="true"></i>
              </button>
            </form>
          </div>
        </div>
      </nav>
    </header>
    <!-- end header section -->
  </div>

  <!-- about section -->

  <section class="about_section layout_padding long_section">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="img-box">
            <img src="images/about-img.png" alt="">
          </div>
        </div>
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                About Us
              </h2>
            </div>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti dolorem eum consequuntur ipsam repellat dolor soluta aliquid laborum, eius odit consectetur vel quasi in quidem, eveniet ab est corporis tempore.
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->


  <!-- info section -->
  <section class="info_section long_section">

    <div class="container">
      <div class="contact_nav">
        <a href="">
          <i class="fa fa-phone" aria-hidden="true"></i>
          <span>
            Call : +01 123455678990
          </span>
        </a>
        <a href="">
          <i class="fa fa-envelope" aria-hidden="true"></i>
          <span>
            Email : demo@gmail.com
          </span>
        </a>
        <a href="">
          <i class="fa fa-map-marker" aria-hidden="true"></i>
          <span>
            Location
          </span>
        </a>
      </div>

      <div class="info_top ">
        <div class="row ">
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="info_links">
              <h4>
                QUICK LINKS
              </h4>
              <div class="info_links_menu">
                <a class="" href="index.html">Home <span class="sr-only">(current)</span></a>
                <a class="" href="about.html"> About</a>
                <a class="" href="furniture.html">Furniture</a>
                <a class="" href="blog.html">Blog</a>
                <a class="" href="contact.html">Contact Us</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-4 col-lg-3 mx-auto">
            <div class="info_post">
              <h5>
                INSTAGRAM FEEDS
              </h5>
              <div class="post_box">
                <div class="img-box">
                  <img src="images/f1.png" alt="">
                </div>
                <div class="img-box">
                  <img src="images/f2.png" alt="">
                </div>
                <div class="img-box">
                  <img src="images/f3.png" alt="">
                </div>
                <div class="img-box">
                  <img src="images/f4.png" alt="">
                </div>
                <div class="img-box">
                  <img src="images/f5.png" alt="">
                </div>
                <div class="img-box">
                  <img src="images/f6.png" alt="">
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="info_form">
              <h4>
                SIGN UP TO OUR NEWSLETTER
              </h4>
              <form action="">
                <input type="text" placeholder="Enter Your Email" />
                <button type="submit">
                  Subscribe
                </button>
              </form>
              <div class="social_box">
                <a href="">
                  <i class="fa fa-facebook" aria-hidden="true"></i>
                </a>
                <a href="">
                  <i class="fa fa-twitter" aria-hidden="true"></i>
                </a>
                <a href="">
                  <i class="fa fa-linkedin" aria-hidden="true"></i>
                </a>
                <a href="">
                  <i class="fa fa-instagram" aria-hidden="true"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end info_section -->


  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </footer>
  <!-- footer section -->


  <!-- jQery -->
  <script src="js/jquery-3.4.1.min.js"></script>
  <!-- bootstrap js -->
  <script src="js/bootstrap.js"></script>
  <!-- custom js -->
  <script src="js/custom.js"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap"></script>
  <!-- End Google Map -->

</body>

</html>

web_resource_g2g/main/templates/main/my_services.html
{% extends "users/base.html" %}
{% block content %}
{% if user.is_authenticated %}
<style>
  :root {
    --primary-color: #EEE8AA ; /* Світло-жовтий колір для заголовків */
    --secondary-color: #333333; /* Темний колір для тексту */
    --background-color: #F5F5F5; /* Світлий фон */
    --table-header-bg: #E0E0E0; /* Фон заголовків таблиці */
    --table-row-bg: #FFFFFF; /* Фон рядків таблиці */
    --table-border-color: #CCCCCC; /* Колір меж таблиці */
}

body {
    background-color: var(--background-color);
    color: var(--secondary-color);
}

h2 {
    color: var(--primary-color);
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
    opacity: 0.7; /* Прозорість таблиці 60% */
}

table th, table td {
    padding: 12px;
    text-align: left;
    border-bottom: 1px solid var(--table-border-color);
}

table th {
    background-color: var(--table-header-bg);

}

table tr {
    background-color: var(--table-row-bg);
}

table tr:hover {
    background-color: #F0F0F0; /* Колір при наведенні */
}
</style>
<!-- Заголовок для першої таблиці -->
{% if not my_services and not my_clients_provide_service %}
    <div class="center-container">
      <h2>Для закріплення за вами послуг як наставник, рекрутер або оренда персонажа, зверніться до адміністратора</h2>
    </div>
{% else %}
    <div class="center-container">
      <h2>Послуги</h2>
    </div>

    <!-- Нова таблиця -->
    <table>
        <thead>
            <tr>
                <th>Клієнт</th>
                <th>Моя послуга</th>
            </tr>
        </thead>
        <tbody>
            {% for mentor in my_clients_provide_service.mentor %}
            <tr>
                <td>{{ mentor }}</td>
                <td>Менторство</td>
            </tr>
            {% endfor %}

            {% for recruiter in my_clients_provide_service.recruiter %}
            <tr>
                <td>{{ recruiter }}</td>
                <td>Рекрутинг</td>
            </tr>
            {% endfor %}

            {% for seller, levels in my_clients_provide_service.renter_lvl.items %}
                {% if levels.renter_lvl1 %}
                    <tr>
                        <td>{{ seller }}</td>
                        <td>Оренда 1 рівня(10%) {{ levels.renter_lvl1|join:", " }}</td>
                    </tr>
                {% endif %}
                {% if levels.renter_lvl2 %}
                    <tr>
                        <td>{{ seller }}</td>
                        <td>Оренда 2 рівня(5%) {{ levels.renter_lvl2|join:", " }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>

    </table>

<!-- Роздільник між таблицями -->
  <br><br>

<!-- Заголовок для другої таблиці -->
    <div class="center-container">
      <h2>Нарахування</h2>
    </div>

    <!-- Існуюча таблиця -->
    <table>
        <thead>
            <tr>
                <th></th>
                <th>Клієнт</th>
                <th>Послуга</th>
                <th>Сервер</th>
                <th>Гра</th>
                <th>Номер замовлення</th>
                <th>Зараховано на баланс</th>
                <th>Час замовлення</th>
                <th>Статус виплати</th>
            </tr>
        </thead>
        <tbody>
            {% for service in my_services %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ service.order.seller.auth_user.username }}</td>
                <td>{{ service.service_type }}</td>
                <td>{{ service.order.server.server_name }}</td>
                <td>{{ service.order.server.game_name }}</td>
                <td>{{ service.order.sold_order_number }}</td>
                <td>{{ service.amount|floatformat:2 }}</td>
                <td>{{ service.order.created_time }}</td>

                {% if service.charged_to_payment_commission and not service.paid_in_salary_commission %}
                <td>Зараховано до оплати</td>
                {% elif service.charged_to_payment_commission and service.paid_in_salary_commission %}
                <td>Виплачено</td>
                {% else %}
                <td>Інформація відсутня</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}
{% endif %}
{% endblock %}

web_resource_g2g/main/templates/main/not_active_orders.html
{% extends "users/base.html" %}
{% block content %}
<div class="center-container">
    <h1>Немає активних замовлень</h1>
</div>
{% endblock %}

web_resource_g2g/main/templates/main/not_found_order.html
{% extends "users/base.html" %}
{% block content %}
<div class="center-container">
    <h1>Не знайдено активних замовлень</h1>
</div>
{% endblock %}

web_resource_g2g/main/templates/main/show_history.html
{% extends "users/base.html" %}
{% block content %}
<style>
  :root {
    --primary-color: #EEE8AA ; /* Світло-жовтий колір для заголовків */
    --secondary-color: #333333; /* Темний колір для тексту */
    --background-color: #F5F5F5; /* Світлий фон */
    --table-header-bg: #E0E0E0; /* Фон заголовків таблиці */
    --table-row-bg: #FFFFFF; /* Фон рядків таблиці */
    --table-border-color: #CCCCCC; /* Колір меж таблиці */
}

body {
    background-color: var(--background-color);
    color: var(--secondary-color);
}

h2 {
    color: var(--primary-color);
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
    opacity: 0.7; /* Прозорість таблиці 60% */
}

table th, table td {
    padding: 12px;
    text-align: left;
    border-bottom: 1px solid var(--table-border-color);
}

table th {
    background-color: var(--table-header-bg);

}

table tr {
    background-color: var(--table-row-bg);
}

table tr:hover {
    background-color: #F0F0F0; /* Колір при наведенні */
}
</style>
<div class="center-container">
    <form method="get" action="{% url 'main:history_orders' %}" style="margin-bottom: 20px;">
        <label for="payment_status">Фільтр по статусу виплати:</label>
        <select name="payment_status" id="payment_status">
            <option value="" {% if not request.GET.payment_status %}selected{% endif %}>Всі</option>
            <option value="charged_to_payment" {% if request.GET.payment_status == "charged_to_payment" %}selected{% endif %}>Зараховано до оплати</option>
            <option value="paid_in_salary" {% if request.GET.payment_status == "paid_in_salary" %}selected{% endif %}>Виплачено</option>
            <option value="cancelled" {% if request.GET.payment_status == "cancelled" %}selected{% endif %}>Скасовано</option>
            <option value="no_info" {% if request.GET.payment_status == "no_info" %}selected{% endif %}>Інформація відсутня</option>
        </select>
        <button type="submit">Фільтрувати</button>
    </form>
    <table>
        <thead>
            <tr>
                <th></th>
                <th>Сервер</th>
                <th>Гра</th>
                <th>Фракція</th>
                <th>Кількість</th>
                <th>Нік персонажа</th>
                <th>Метод доставки</th>
                <th>Ціна за одиницю</th>
                <th>Зараховано на баланс</th>
                <th>Баланс</th>
                <th>Час замовлення</th>
                <th>Номер замовлення</th>
                <th>Статус виконання замовлення</th>
                <th>Статус виплати</th>

            </tr>
        </thead>
        <tbody>
            {% for item in orders_history %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.order.server.server_name }}</td>
                    <td>{{ item.order.server.game_name}}</td>
                    <td>{{ item.order.server.fraction }}</td>
                    <td>{{ item.order.quantity }}</td>
                    <td>{{ item.order.character_name }}</td>
                    <td>{{ item.order.trade_mode }}</td>
                    <td>{{ item.order.price_unit }}</td>
                    <td>{{ item.order.earned_without_admins_commission|floatformat:2 }}</td>
                    <td>{{ item.current_balance|floatformat:2}}</td>
                    <td>{{ item.order.created_time }}</td>
                    <td>{{ item.order.sold_order_number }}</td>
                    {% if item.order.status == "CANCEL_REQUESTED" %}
                    <td>Скасовано</td>
                    {% elif not item.order.download_video_status %}
                    <td>Очикується завантаження відео</td>
                    {% else %}
                    <td>Завершено</td>
                    {% endif %}

                    {% if item.order.charged_to_payment and not item.order.paid_in_salary %}
                    <td>Зараховано до оплати</td>
                    {% elif item.order.charged_to_payment and item.order.paid_in_salary %}
                    <td>Виплачено</td>
                    {% elif item.order.status == "CANCEL_REQUESTED" %}
                    <td>Скасовано</td>
                    {% else %}
                    <td>Інформація відсутня</td>
                    {% endif %}

                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

web_resource_g2g/main/templates/main/show_order_info.html
{% extends "users/base.html" %}
{% block content %}
<div class="center-container d-flex justify-content-center align-items-center flex-column"> {# Додано класи flexbox #}
    <table >
      <thead>
          <tr>
              <th></th>
              <th>Сервер</th>
              <th>Гра</th>
              <th>Фракція</th>
              <th>Кількість</th>
              <th>Нік персонажа</th>
              <th>Метод доставки</th>
              <th>Ціна за одиницю</th>
              <th>Заробіток</th>
              <th>Статус замовлення</th>


          </tr>
      </thead>
      <tbody>
          <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ order.server.server_name }}</td>
              <td>{{ order.server.game_name}}</td>
              <td>{{ order.server.fraction }}</td>
              <td id="quantity_gold">{{ order.quantity }}</td>
              <td>{{ order.character_name }}</td>
              <td>{{ order.trade_mode }}</td>
              <td>{{ price_unit }}</td>
              <td>{{order.earned_without_admins_commission|floatformat:2 }}</td>
              {% if not order.download_video_status %}
              <td>Очікується завантаження відео</td>
              {% else %}
              <td>Завершено</td>
              {% endif %}
          </tr>
      </tbody>
    </table>
    <button id="uploadButton">Завантажити відео</button>

    <div id="uploadForm" style="display: none;">  <form method="post" enctype="multipart/form-data" id="videoForm">
        {% csrf_token %}
        <input type="file" name="video" id="videoFile" accept="video/*">
        <label for="sent_gold">Введіть кількість надісланого золота:</label>
        <input type="number" id="sent_gold" name="sent_gold" style="width: 8ch;" required>
        <button type="button" id="submitButton">Відправити</button>
        <button type="button" id="cancelUpload">Скасувати</button>
      </form>
    </div>
</div>

<script>
    // Отримуємо посилання на елементи DOM
    const uploadButton = document.getElementById('uploadButton');
    const uploadForm = document.getElementById('uploadForm');
    const videoFile = document.getElementById('videoFile');
    const submitButton = document.getElementById('submitButton');
    const progressDiv = document.getElementById('progress');
    const cancelUpload = document.getElementById('cancelUpload'); // Отримуємо кнопку "Скасувати"
    const sent_goldInput = document.getElementById('sent_gold');
    const quantity = document.getElementById('quantity_gold');



    uploadButton.addEventListener('click', () => {
        uploadForm.style.display = 'block';
        uploadButton.style.display = 'none';
    });

    // Додаємо обробник події для кнопки "Скасувати"
    cancelUpload.addEventListener('click', () => {
    uploadForm.style.display = 'none'; // Ховаємо форму
    uploadButton.style.display = 'block'; // Показуємо кнопку "Завантажити відео"
    videoFile.value = ''; // Очищаємо вибраний файл
    sent_goldInput.value = ''; // Очищаємо поле вводу кількості золота
    });

    submitButton.addEventListener('click', () => {
        const file = videoFile.files[0];
        const sent_gold = sent_goldInput.value;
        const quantity_gold = parseInt(quantity.textContent, 10);

        if (sent_gold > quantity_gold) { // Перевірка тут
            alert("Відправлене золото не може перевищувати замовлене");
            return; // Зупиняємо виконання
        }

        if (!sent_gold) {
            alert("Будь ласка, введіть кількість відправленого золота.");
            return;
        }

        if (isNaN(sent_gold)) {
            alert("кількість відправленого золота має містити тільки цифри.");
            return;
        }

        if (!file) {
            alert("Будь ласка, оберіть файл.");
            return;
        }

        uploadFile(file, sent_gold); // Передаємо sent_gold у функцію uploadFile
    });

    function uploadFile(file, sent_gold) { // sent_gold тепер аргумент функції
        const formData = new FormData();
        formData.append('video', file);
        formData.append('sent_gold', sent_gold);


        const xhr = new XMLHttpRequest(); // Створюємо новий XMLHttpRequest
        xhr.open('POST', '{% url 'main:upload_video' sold_order_number=sold_order_number %}', true); // Налаштовуємо запит: метод POST, URL '/upload', асинхронний режим
        xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');

        xhr.upload.onprogress = function(event) {
            if (event.lengthComputable) {
                const percentComplete = (event.loaded / event.total) * 100;
                progressDiv.textContent = `Завантажено: ${percentComplete.toFixed(2)}%`;
            }
        };

        xhr.onload = function() {
            if (xhr.status === 200) {
                alert('Відео успішно завантажено!');
                uploadForm.style.display = 'none';
                window.location.href = '{% url 'main:start_page' %}'
            } else {
                alert('Помилка завантаження. ' + xhr.responseText); // Виводимо текст помилки з сервера
            }
        };
                xhr.onerror = function() {
          alert('Помилка з\'єднання з сервером.');
        };

        xhr.send(formData);
    }
</script>
{% endblock %}