web_resource_g2g/internal_market/urls.py
from django.urls import path
from . import views

app_name = 'internal_market'

urlpatterns = [
    path('market/', views.main_page, name='main_page'),
    path('create_order_from_form/', views.create_order_from_form, name='create_order_from_form'),

]

web_resource_g2g/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.start_page, name='start_page'),
    path('update_table_data/', views.update_table_data, name='update_table_data'),
    path('add_server/', views.add_server, name='add_server'),
    path('handle_option_change/', views.handle_option_change, name='handle_option_change'),
    path('show_order_info/', views.show_order_info, name='show_order_info'),
    path('upload_video/<int:sold_order_number>/', views.upload_video, name='upload_video'),
    path('history_orders/', views.show_history_orders, name='history_orders'),
    path('balance/', views.show_balance, name='balance'),
    path("delete_server/", views.delete_server, name="delete_server"),
    path("my_services/", views.my_services, name="my_services"),
]

web_resource_g2g/web_resource_g2g/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("", include("users.urls")),
    path("internal_market/", include("internal_market.urls")),
] +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web_resource_g2g/internal_market/models.py
from django.db import models
from django.utils import timezone

from main import models as main_models


class InternalOrder(models.Model):
    server = models.ForeignKey(main_models.ServerUrls, on_delete=models.CASCADE)
    internal_seller = models.ForeignKey(main_models.Sellers, on_delete=models.CASCADE)
    internal_buyer = models.ForeignKey(main_models.Sellers, on_delete=models.CASCADE,
                                       null=True, blank=True, related_name='internal_buyer')
    status = models.CharField(max_length=255, default='DELIVERING')
    character_name = models.CharField(max_length=255)
    sold_order_number = models.BigIntegerField(unique=True)
    quantity = models.IntegerField()
    sent_gold = models.IntegerField(null=True, blank=True, db_default=0)
    price_unit = models.DecimalField(max_digits=10, decimal_places=3, default=0)
    total_amount = models.DecimalField(max_digits=10, decimal_places=3, default=0)
    earned_without_admins_commission = models.DecimalField(max_digits=10, decimal_places=3, default=0)
    owner_commission = models.DecimalField(max_digits=10, decimal_places=3, default=0)
    technical_commission = models.DecimalField(max_digits=10, decimal_places=3, default=0)
    trade_mode = models.CharField(max_length=255)
    created_time = models.DateTimeField(default=timezone.now)
    send_message = models.BooleanField(default=False)
    path_to_video = models.CharField(max_length=255, blank=True, default='')
    download_video_status = models.BooleanField(default=False, null=True)
    charged_to_payment = models.BooleanField(default=False)
    paid_in_salary = models.BooleanField(default=False)
    paid_to_owner = models.BooleanField(default=False)
    paid_to_technical = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.internal_seller.auth_user.username} № {self.sold_order_number} - {self.total_amount}$"

    def save(self, *args, **kwargs):
        if not self.sold_order_number:
            now = timezone.now()
            self.sold_order_number = int(now.strftime('%d%m%H%M%S%f')[:-4])
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Внутрішнє замовлення"
        verbose_name_plural = "Внутрішні замовлення"

web_resource_g2g/internal_market/views.py
import json

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from main.utils.logger_config import logger
from internal_market import crud as internal_market_crud
from django.http import JsonResponse, HttpResponseNotAllowed, HttpResponse


@login_required(login_url='users:login')
def main_page(request):
    lots_for_sale = internal_market_crud.get_lots_for_sale(request.user.id)
    logger.info(f"lots_for_sale__{lots_for_sale}")
    return render(request, 'internal_market/internal_market_main.html',
                  context={"lots_for_sale": lots_for_sale})


def create_order_from_form(request):
    internal_order_data = json.loads(request.body)
    response = internal_market_crud.create_order(request.user.id, internal_order_data)
    return JsonResponse(response)

web_resource_g2g/internal_market/templates/internal_market/internal_market_main.html
{% extends "users/base.html" %}
{% load static %}
{% block content %}
<style>
  :root {
    --primary-color: #EEE8AA ; /* Світло-жовтий колір для заголовків */
    --secondary-color: #333333; /* Темний колір для тексту */
    --background-color: #d4dde4; /* Світлий фон */
    --table-header-bg: #E0E0E0; /* Фон заголовків таблиці */
    --table-row-bg: #FFFFFF; /* Фон рядків таблиці */
    --table-border-color: #CCCCCC; /* Колір меж таблиці */
}

body {
    background-color: var(--background-color);
    color: var(--secondary-color);
}

h2 {
    color: var(--primary-color);
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
    opacity: 0.7; /* Прозорість таблиці 60% */
}

table th, table td {
    padding: 12px;
    text-align: left;
    border-bottom: 1px solid var(--table-border-color);
}

table th {
    background-color: var(--table-header-bg);

}

table tr {
    background-color: var(--table-row-bg);
}

table tr:hover {
    background-color: #F0F0F0; /* Колір при наведенні */
}
  #orderForm {
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  border-radius: 8px;
}

#orderForm h2 {
  margin-top: 0;
}

#orderForm label {
  display: block;
  margin-bottom: 5px;
}

#orderForm input {
  width: 100%;
  padding: 8px;
  margin-bottom: 10px;
  border: 1px solid #ccc;
  border-radius: 4px;
}

#orderForm button {
  padding: 8px 16px;
  margin-right: 10px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

#orderForm button[type="submit"] {
  background-color: #4CAF50;
  color: white;
}

#orderForm button[type="button"] {
  background-color: #f44336;
  color: white;
}
</style>
<div class="center-container">
  <table>
	<thead>
	<tr>
	  <th></th>
	  <th>Сервер</th>
	  <th>Гра</th>
	  <th>Ціна</th>
	  <th>Кількість</th>
	  <th>Доставка</th>
	</tr>
	</thead>
	<tbody>
	{% for lot in lots_for_sale %}
	<tr id="{{ lot.id }}" class="clickable-row" data-seller-id="{{ lot.sellers }}" data-server-urls="{{ lot.server_urls }}" data-face-to-face-trade="{{ lot.face_to_face_trade }}" data-mail-delivery="{{ lot.mail_delivery }}">
	  <td>{{ forloop.counter }}</td>
	  <td><input type="text" id="server-{{ lot.id }}" value="{{ lot.server_name }}" title="{{ lot.server_name }}"
				 readonly></td>
	  <td><input type="text" id="game-{{ lot.id }}" value="{{ lot.game_name }}" title="{{ lot.game_name }}" readonly></td>
	  <td><input type="text" id="price-{{ lot.id }}" value="{{ lot.price }}" readonly></td>
	  <td><input type="text" id="stock-{{ lot.id }}"
				 value="{% if lot.game_name == 'Cataclysm' %}{{ lot.stock }}K{% else %}{{ lot.stock }}{% endif %}"
				 readonly></td>
	  <td>
		{% if lot.mail_delivery %}
		  <i class="fas fa-envelope" style="font-size: 150%; color: lightblue;"  title="Mail"></i>
		{% endif %}
		{% if lot.face_to_face_trade %}
		  <i class="fa-solid fa-people-carry-box" style="font-size: 150%; color: #3CB371;" title="Trade"></i>
		{% endif %}
	  </td>
	</tr>
	{% endfor %}
	</tbody>
  </table>
</div>
<script>
document.addEventListener("DOMContentLoaded", function () {
  const rows = document.querySelectorAll(".clickable-row");

  rows.forEach((row) => {
    row.addEventListener("click", function () {
      const lotId = row.id;
      const sellerId = row.dataset.sellerId;
      const serverUrls = row.dataset.serverUrls;
      const serverName = row.querySelector(`input[id^="server-"]`).value;
      const gameName = row.querySelector(`input[id^="game-"]`).value;
      const priceString = row.querySelector(`input[id^="price-"]`).value.replace(",", ".");
      const price = parseFloat(priceString);
      const stockText = row.querySelector(`input[id^="stock-"]`).value;
      const stock = parseInt(stockText.replace("K", "").trim());
	  const faceToFaceTrade = row.dataset.faceToFaceTrade === "True"; // Отримуємо значення з dataset
      const mailDelivery = row.dataset.mailDelivery === "True"; // Отримуємо значення з dataset

      showOrderForm(lotId, sellerId, serverName, gameName, price, stock, serverUrls, faceToFaceTrade, mailDelivery);
    });
  });

  function showOrderForm(lotId, sellerId, serverName, gameName, price, stock, serverUrls, faceToFaceTrade, mailDelivery) {
    closeOrderForm();


	// Визначаємо доступні способи доставки
	const deliveryMethods = [];
	if (faceToFaceTrade) {
	  deliveryMethods.push({ value: "Trade", label: "Face to face trade" });
	}
	if (mailDelivery) {
	  deliveryMethods.push({ value: "Mail", label: "Mail" });
	}

	// Генеруємо HTML для вибору способу доставки
	const deliveryMethodOptions = deliveryMethods
	  .map((method) => `<option value="${method.value}">${method.label}</option>`)
	  .join("");

	const formHtml = `
	  <div id="orderForm" style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);
	   background-image: url('{% static 'images/market_back.jpg' %}'); background-size: cover;
	   background-repeat: no-repeat; padding: 20px; border: 1px solid #ccc; z-index: 1000;">
		<h3>Замовлення на сервері: ${serverName}</h3><br><br><br>
		<form id="orderFormContent">
		  <label for="characterName" style="color: #2c3e50; font-family: 'Arial', sans-serif; font-size: 1.1em;">Ім'я персонажа:</label>
		  <input type="text" id="characterName" name="characterName" style="width: 30ch; background-color: #ffffff; color: #2c3e50; border: 1px solid #bdc3c7; padding: 8px; border-radius: 4px; font-family: 'Arial', sans-serif;" required><br><br>

		  <label for="deliveryMethod" style="color: #2c3e50; font-family: 'Arial', sans-serif; font-size: 1.1em;">Спосіб доставки:</label>
		  <select id="deliveryMethod" name="deliveryMethod" style="background-color: #ffffff; color: #2c3e50; border: 1px solid #bdc3c7; padding: 8px; border-radius: 4px; font-family: 'Arial', sans-serif;">
			${deliveryMethodOptions}
		  </select><br><br>

		  <label for="quantity" style="color: #2c3e50; font-family: 'Arial', sans-serif; font-size: 1.1em;">Кількість золота:</label>
		  <input type="number" id="quantity" name="quantity" min="1" max="${stock}" value="1" style="width: 10ch; background-color: #ffffff; color: #2c3e50; border: 1px solid #bdc3c7; padding: 8px; border-radius: 4px; font-family: 'Arial', sans-serif;" required>
		  <span style="margin-left: 10px;">Доступно: <span style="color: #545352; font-family: 'Arial', sans-serif; font-size: 1.4em;">${stock}</span></span><br>
		  <span>Поточна ціна за одиницю: <span style="color: #545352; font-family: 'Arial', sans-serif; font-size: 1.4em;">${price.toFixed(2)}</span></span><br><br>

		  <label style="color: #2c3e50; font-family: 'Arial', sans-serif; font-size: 1.1em;">Загальна вартість:</label>
		  <span id="totalCost" style="font-size: 2.0em; font-weight: bold; color: #27ae60; text-decoration: underline;">${price.toFixed(2)}</span> <br><br>

		  <button type="submit" style="background-color: #27ae60; color: white; padding: 10px 20px; border: none; border-radius: 5px; font-family: 'Arial', sans-serif; font-size: 1em; cursor: pointer;">Замовити</button>
		  <button type="button" id="cancelOrder" style="background-color: #e74c3c; color: white; padding: 10px 20px; border: none; border-radius: 5px; font-family: 'Arial', sans-serif; font-size: 1em; cursor: pointer;">Скасувати</button>
		</form>
	  </div>
	`;

    document.body.insertAdjacentHTML("beforeend", formHtml);

    const quantityInput = document.getElementById("quantity");
    const totalCostElement = document.getElementById("totalCost");
    const deliveryMethodSelect = document.getElementById("deliveryMethod");

    const updateTotalCost = () => {
      const quantity = parseInt(quantityInput.value) || 1;
      const totalCost = quantity * price;
      totalCostElement.textContent = totalCost.toFixed(2);
    };

    quantityInput.addEventListener("input", updateTotalCost);
    quantityInput.addEventListener("change", updateTotalCost);
    updateTotalCost();

    document.getElementById("cancelOrder").addEventListener("click", closeOrderForm);

    document.getElementById("orderFormContent").addEventListener("submit", function (event) {
      event.preventDefault();
      const characterName = document.getElementById("characterName").value;
      const quantity = parseInt(document.getElementById("quantity").value);
      const totalCost = (quantity * price).toFixed(2);
      const deliveryMethod = deliveryMethodSelect.value;

      // Відображення власного вікна підтвердження
      showConfirmationModal(serverName, characterName, quantity, totalCost, deliveryMethod, sellerId, lotId, price, gameName, serverUrls);
    });
  }

  function showConfirmationModal(serverName, characterName, quantity, totalCost, deliveryMethod, sellerId, lotId, price, gameName, serverUrls) {
    const confirmationHtml = `
      <div id="confirmationModal" style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);
       background-color: #d4dde4; padding: 20px; border: 1px solid #ccc; z-index: 1001; box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);">
        <h3>Підтвердження замовлення</h3>
        <p>Сервер: ${serverName}</p>
        <p>Персонаж: ${characterName}</p>
        <p>Кількість: ${quantity}</p>
        <p>Загальна вартість: ${totalCost}</p>
        <p>Спосіб доставки: ${deliveryMethod}</p>
        <button id="confirmOrder" style="background-color: #27ae60; color: white; padding: 10px 20px; border: none; border-radius: 5px; font-family: 'Arial', sans-serif; font-size: 1em; cursor: pointer;">Підтвердити</button>
        <button id="cancelConfirmation" style="background-color: #e74c3c; color: white; padding: 10px 20px; border: none; border-radius: 5px; font-family: 'Arial', sans-serif; font-size: 1em; cursor: pointer;">Скасувати</button>
      </div>
    `;

    document.body.insertAdjacentHTML("beforeend", confirmationHtml);

  document.getElementById("confirmOrder").addEventListener("click", function () {
	const orderData = {
	  seller_id: sellerId,
	  server_id: serverUrls,
	  order_quantity: quantity,
	  total_amount: totalCost,
	  character_name: characterName,
	  lot_id: lotId,
	  server_name: serverName,
	  unit_price: price,
	  game_name: gameName,
	  delivery_method: deliveryMethod
	};

	fetch("{% url 'internal_market:create_order_from_form' %}", {
	  method: "POST",
	  headers: {
		"Content-Type": "application/json",
		"X-CSRFToken": "{{ csrf_token }}",
	  },
	  body: JSON.stringify(orderData),
	})
	.then(response => response.json())
	.then(data => {
        if (data.success) {
		  // Відображення повідомлення в залежності від способу доставки
		  if (deliveryMethod === "Mail") {
			alert("Замовлення успішно створено! Ви отримаєте сповіщення в телеграм, коли замовлення буде виконано.");
		  } else if (deliveryMethod === "Trade") {
			alert("Замовлення успішно створено! Підготуйте кілька речей синього класу для обміну та чекайте біля аукціону центрального міста. Протягом 10 хвилин надійде запрошення на обмін. У разі виникнення питань, звертайтеся до адміністратора.");
		  } else {
			alert("Замовлення успішно створено!");
		  }
		  closeOrderForm();
		  closeConfirmationModal();
		  window.location.reload(); // Оновлення сторінки

		} else {
            // Виводимо повідомлення про помилку
            if (data.message) {
                alert(data.message);
            } else {
                alert("Виникла помилка. Спробуйте ще раз.");
            }
      }
    })
    .catch((error) => {
      console.error("Помилка:", error);
      alert("Сталася помилка при відправці запиту.");
	  });
  });

    document.getElementById("cancelConfirmation").addEventListener("click", closeConfirmationModal);
  }

  function closeConfirmationModal() {
    const modal = document.getElementById("confirmationModal");
    if (modal) {
      modal.remove();
    }
  }

  function closeOrderForm() {
    const form = document.getElementById("orderForm");
    if (form) {
      form.remove();
    }
  }
});
</script>

{% endblock %}